name: Code Review Workflow

on:
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        required: true

jobs:
  code_review:
    name: OpenAI Review
    if: github.event.pull_request.user.name != 'renovate'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Review
        uses: cawcaw253/ai-review-action@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
